### ISSUE TITLE
Bug when empty user_msa.fasta

### ISSUE THREAD

**Issue by moritzbuck** [Ecogenomics/GTDBTk#119] opened 2019-04-30 05:29 UTC
Bug if all genomes of a specific marker set have too few amino-acids in alignment.

```[2019-04-30 07:09:08] INFO: Aligning markers in 614 genomes with 5 threads.
[2019-04-30 07:09:08] INFO: Processing 604 genomes identified as bacterial.
[2019-04-30 07:09:10] INFO: Read concatenated alignment for 17413 GTDB genomes.
[2019-04-30 07:10:19] INFO: Masking columns of multiple sequence alignment using canonical mask.
[2019-04-30 07:11:05] INFO: Masked alignment from 41155 to 5035 AA.
[2019-04-30 07:11:05] INFO: 557 user genomes have amino acids in <10.0% of columns in filtered MSA.
[2019-04-30 07:11:05] INFO: Creating concatenated alignment for 17460 GTDB and user genomes.
[2019-04-30 07:11:06] INFO: Creating concatenated alignment for 47 user genomes.
[2019-04-30 07:11:06] INFO: Processing 10 genomes identified as archaeal.
[2019-04-30 07:11:06] INFO: Read concatenated alignment for 845 GTDB genomes.
[2019-04-30 07:11:07] INFO: Masking columns of multiple sequence alignment using canonical mask.
[2019-04-30 07:11:09] INFO: Masked alignment from 32675 to 5024 AA.
[2019-04-30 07:11:09] INFO: 10 user genomes have amino acids in <10.0% of columns in filtered MSA.
[2019-04-30 07:11:09] INFO: Creating concatenated alignment for 845 GTDB and user genomes.
[2019-04-30 07:11:09] INFO: Creating concatenated alignment for 0 user genomes.
[2019-04-30 07:11:09] INFO: Done.
Traceback (most recent call last):
  File "/home/moritz/.local/lib/python2.7/site-packages/gtdbtk-0.2.2-py2.7.egg/gtdbtk/biolib_lite/seq_io.py", line 163, in read_fasta_seq
    yield seq_id, ''.join(seq).replace(' ', '')
TypeError


[Error] Failed to process sequence file: temp/gtdbtk.ar122.user_msa.fasta

Controlled exit resulting from an unrecoverable error or warning.
```
can be solved by changing line 235 of classify.py to : 
`if os.stat(user_msa_file).st_size == 0 or not os.path.exists(user_msa_file):`

Not sure if is not a more elegant way to solve it so I just leave it here!

Thanks guys anyhow!

**Comment by pchaumeil** [comment] 2019-05-03 02:52
Hello Moritz,
Thanks for your email.
Please note this error is a duplicate of #108 and the code fix will be available in the next GTDB-Tk release.

Regards,
Pierre

**Comment by pchaumeil** [comment] 2019-06-21 03:28
GTDB-Tk resolves this issue

**Closed by pchaumeil** 2019-06-21 03:28 UTC
