### ISSUE TITLE
Option for GTDB-Tk to find the closest reference genome using ANI

### ISSUE THREAD

**Issue by aaronmussig** [Ecogenomics/GTDBTk#180] opened 2019-08-13 05:10 UTC
There was a suggestion for GTDB-Tk to find the closest reference genome when there is no FastANI closest genome.

Given this is a computationally expensive task it would be bundled as a separate command (with a warning displayed). Perhaps calculations could start from the GTDB-Tk classify node and traverse the tree outwards.

Alternatively, users can do this manually using the reference package `fastani/database` genome directory.

**Comment by dparks1134** [comment] 2019-08-13 15:26
Arguably one shouldn't be considering ANI once you are outside of intra-genus comparisons. Generally, AAI is recommended at this point. That said, if it can be put into place without much effort it certainly isn't going to do any harm.

**Comment by pchaumeil** [comment] 2019-11-28 23:57
Duplicate of #191

**Closed by pchaumeil** 2019-11-28 23:57 UTC
Labels: suggestion
